name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /var/www/html
          echo '<!DOCTYPE html><html><head><title>Live from GitHub</title></head><body style="text-align:center;font-family:sans-serif;"><h1>🚀 Deployed from GitHub Actions</h1><p>This file was updated on: $(date)</p></body></html>' | sudo tee index.html > /dev/null
